# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GenerateTool(object):
    def setupUi(self, GenerateTool):
        GenerateTool.setObjectName("GenerateTool")
        GenerateTool.resize(324, 234)
        GenerateTool.setMinimumSize(QtCore.QSize(324, 234))
        GenerateTool.setMaximumSize(QtCore.QSize(324, 324))
        self.ToolName_label = QtWidgets.QLabel(GenerateTool)
        self.ToolName_label.setGeometry(QtCore.QRect(80, 10, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.ToolName_label.setFont(font)
        self.ToolName_label.setObjectName("ToolName_label")
        self.NumberOfParticipant_label = QtWidgets.QLabel(GenerateTool)
        self.NumberOfParticipant_label.setGeometry(QtCore.QRect(40, 70, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NumberOfParticipant_label.setFont(font)
        self.NumberOfParticipant_label.setObjectName("NumberOfParticipant_label")
        self.Generate_pushButton = QtWidgets.QPushButton(GenerateTool)
        self.Generate_pushButton.setGeometry(QtCore.QRect(120, 140, 75, 41))
        self.Generate_pushButton.setObjectName("Generate_pushButton")
        self.Notification_lineEdit = QtWidgets.QLineEdit(GenerateTool)
        self.Notification_lineEdit.setGeometry(QtCore.QRect(12, 189, 301, 41))
        self.Notification_lineEdit.setReadOnly(True)
        self.Notification_lineEdit.setObjectName("Notification_lineEdit")
        self.NumberOfParticipant_spinBox = QtWidgets.QSpinBox(GenerateTool)
        self.NumberOfParticipant_spinBox.setGeometry(QtCore.QRect(190, 80, 42, 22))
        self.NumberOfParticipant_spinBox.setMaximum(100)
        self.NumberOfParticipant_spinBox.setObjectName("NumberOfParticipant_spinBox")

        self.retranslateUi(GenerateTool)
        QtCore.QMetaObject.connectSlotsByName(GenerateTool)

    def retranslateUi(self, GenerateTool):
        _translate = QtCore.QCoreApplication.translate
        GenerateTool.setWindowTitle(_translate("GenerateTool", "IP Tool"))
        self.ToolName_label.setText(_translate("GenerateTool", "Import Tool Gen"))
        self.NumberOfParticipant_label.setText(_translate("GenerateTool", "Number Of Participants :"))
        self.Generate_pushButton.setText(_translate("GenerateTool", "GEN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GenerateTool = QtWidgets.QWidget()
    ui = Ui_GenerateTool()
    ui.setupUi(GenerateTool)
    GenerateTool.show()
    sys.exit(app.exec_())
